name: Validar Estructura
on: 
  pull_request:
    branches: [main]
  push:
    branches-ignore: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Validar nombre de branch
        run: |
          # Obtener el nombre de la branch
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            branch="${{ github.head_ref }}"
          else
            branch="${GITHUB_REF#refs/heads/}"
          fi
          
          echo "🔍 Validando branch: $branch"
          
          # Validar que siga la estructura correcta
          if [[ ! $branch =~ ^(feature|bugfix|hotfix|release|docs|refactor)\/[a-z0-9-]+$ ]] && [[ $branch != "main" ]]; then
            echo "❌ ERROR: Branch '$branch' no sigue la convención"
            echo ""
            echo "🌿 RAMAS - Nomenclatura Clara"
            echo ""
            echo "📋 Formato recomendado:"
            echo "   tipo/descripcion-breve-kebab-case"
            echo ""
            echo "📋 Tipos de rama:"
            echo "   • feature/ - Nuevas funcionalidades"
            echo "   • bugfix/ - Corrección de bugs"
            echo "   • hotfix/ - Correcciones urgentes en producción"
            echo "   • release/ - Preparación de versiones"
            echo "   • docs/ - Solo documentación"
            echo "   • refactor/ - Refactorización"
            echo ""
            echo "✅ Ejemplos BUENOS:"
            echo "   • feature/user-authentication"
            echo "   • feature/payment-integration"
            echo "   • bugfix/login-validation-error"
            echo "   • hotfix/critical-security-patch"
            echo "   • release/v2.1.0"
            echo "   • docs/api-documentation"
            echo "   • refactor/database-queries"
            echo ""
            echo "❌ Ejemplos MALOS:"
            echo "   • juan"
            echo "   • mi-rama"
            echo "   • test"
            echo "   • branch1"
            echo "   • feature-nueva"
            exit 1
          fi
          
          echo "✅ Nombre de branch válido: $branch"
          
      - name: Validar mensajes de commits
        run: |
          echo "🔍 Validando mensajes de commits..."
          
          # Obtener commits desde main
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            commits=$(git log --oneline origin/main..HEAD --pretty=format:"%s")
          else
            commits=$(git log --oneline origin/main..HEAD --pretty=format:"%s" 2>/dev/null || git log --oneline -1 --pretty=format:"%s")
          fi
          
          if [ -z "$commits" ]; then
            echo "✅ No hay commits nuevos para validar"
            exit 0
          fi
          
          invalid_commits=""
          
          while IFS= read -r commit_msg; do
            # Validar formato: "tipo: descripción breve" (sin paréntesis de scope)
            if [[ ! $commit_msg =~ ^(feat|fix|docs|style|refactor|test|chore): .+ ]]; then
              echo "❌ Commit inválido (formato): '$commit_msg'"
              invalid_commits="$invalid_commits\n  • $commit_msg (formato incorrecto)"
            else
              # Validar que esté en inglés (no contiene caracteres especiales del español)
              description=$(echo "$commit_msg" | sed 's/^[^:]*: //')
              if [[ $description =~ [ñáéíóúü¿¡] ]]; then
                echo "❌ Commit inválido (idioma): '$commit_msg'"
                invalid_commits="$invalid_commits\n  • $commit_msg (debe estar en inglés)"
              else
                echo "✅ Commit válido: '$commit_msg'"
              fi
            fi
          done <<< "$commits"
          
          if [ ! -z "$invalid_commits" ]; then
            echo ""
            echo "❌ ERROR: Commits con formato incorrecto:"
            echo -e "$invalid_commits"
            echo ""
            echo "📋 COMMITS - Formato Estándar"
            echo ""
            echo "📋 Estructura básica:"
            echo "   Tipo: descripción breve"
            echo ""
            echo "📋 Tipos de commit:"
            echo "   • feat: Nueva funcionalidad"
            echo "   • fix: Corrección de bugs"
            echo "   • docs: Documentación"
            echo "   • style: Formato/estilo (sin cambios de lógica)"
            echo "   • refactor: Refactorización de código"
            echo "   • test: Agregar o modificar tests"
            echo "   • chore: Tareas de mantenimiento"
            echo ""
            echo "✅ Ejemplos BUENOS:"
            echo "   • feat: add JWT token validation"
            echo "   • fix: resolve password reset bug"
            echo "   • docs: update installation instructions"
            echo "   • refactor: simplify user data processing"
            echo "   • test: add unit tests for date helpers"
            echo ""
            echo "❌ Ejemplos MALOS:"
            echo "   • hola (no está en inglés)"
            echo "   • fix (falta descripción)"
            echo "   • cambios varios (no está en inglés)"
            echo "   • update (falta tipo)"
            echo "   • feat: añadir funcionalidad (no está en inglés)"
            echo "   • fix: corregir bug (no está en inglés)"
            echo ""
            echo "⚠️  IMPORTANTE: Los commits deben estar en INGLÉS"
            exit 1
          fi
          
          echo "✅ Todos los commits tienen formato válido"
